Improve image build time
Unstructured-IO/unstructured-api pull request #99
Opened 2023-05-05 21:15 UTC by tabossert

- Builds from pre built custom image
- Has some fixes from other branches (SSL, Makefile changes)

2023-05-10 21:35 UTC, tabossert commented
I still need to get the M-series builds going, but this is a start.  We can use the same base image for unstructured and other codebases

2023-05-11 20:48 UTC, ryannikolaidis approved these changes
LGTM!

```

2023-05-11 21:24 UTC, cragwolfe commented on README.md
> +    - make install-detectron2
nit: think this block fits more naturally combined with " Run make install" line a few lines below. I.e., "if image and high resolution pdf extraction is required, also run `make install-detectron2`"

... and actually ...

the default image layout model probably won't be detectron2, so i'd name it something more abstract to begin with.

2023-05-11 22:43 UTC, ryannikolaidis requested changes
Actually maybe worth holding for M series changes? That way we don't regress until then?

2023-05-11 23:42 UTC, tabossert commented
Sounds good, I will get M series working tomorrow morning

2023-05-25 23:30 UTC, ryannikolaidis commented
testing arm build now

2023-05-25 23:37 UTC, ryannikolaidis approved these changes
LGTM! 🥳

ran:

```
>> make docker-build
>> docker inspect pipeline-family-general-dev:latest | grep Arch
        "Architecture": "arm64",

>> make docker-start-api 
docker run -p 8000:8000 --mount type=bind,source=/Users/ryannikolaidis/Development/unstructured/unstructured-api,target=/home/notebook-user/local -t --rm pipeline-family-general-dev:latest --log-config logger_config.yaml --host 0.0.0.0 --port 8000
2023-05-25 23:34:45,094 uvicorn.error INFO Started server process [1]
2023-05-25 23:34:45,094 uvicorn.error INFO Waiting for application startup.
2023-05-25 23:34:45,094 uvicorn.error INFO Application startup complete.
2023-05-25 23:34:45,096 uvicorn.error INFO Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
[ran request]
2023-05-25 23:34:58,501 172.17.0.1:55024 POST /general/v0/general HTTP/1.1 - 200 OK
```

2023-05-26 00:59 UTC, merged